dist: trusty
sudo: false

language: python
python:
  - 3.5
  - 3.5-dev
  - 3.6
  - 3.6-dev
  - 3.7-dev

install:
  - pip install codecov

script:
  - coverage run --source=flexiconf -m unittest

after_success:
  - codecov

deploy:
  provider: pypi
  user: "Viers"
  password: "$PYPI_PASSWORD"
  skip_existing: true